# docker-compose.yml

services:
  web:
    build: .
    command: sh -c "
        python manage.py makemigrations &&  
        python manage.py migrate &&
        daphne -b 0.0.0.0 -p 8000 skillbridge.asgi:application
      "
    volumes:
      - ./server:/usr/src/app
    ports:
      - "8000:8000"
      - "8001:8001"
    
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DB_ENGINE}
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USERNAME: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}

    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: skillbridge_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    command: sh -c "celery -A skillbridge worker --loglevel=info"
    depends_on:
      - redis
    env_file:
      - .env

  celery-beat:
    build: .
    command: sh -c "celery -A skillbridge beat --loglevel=info"
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  postgres_data:
